version: "3.8"
services:
  thegull:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # 호스트의 5000번 포트를 컨테이너의 5000번 포트에 연결
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - FLASK_APP=slack_test.py
    env_file:
      - .env
    volumes:
      - ${LOCAL_PATH}:/mnt/data # .env 파일의 LOCAL_PATH 변수를 사용
#  nginx:
#    image: nginx:latest
#    ports:
#      - "80:80" # 호스트의 80번 포트를 NGINX 컨테이너의 80번 포트에 연결
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf # NGINX 설정 파일 마운트
#    depends_on:
#      - flask_app
