apiVersion: v1
kind: Service
metadata:
  name: thegull-service
spec:
  type: NodePort # 노드의 IP 주소를 통해 접근 가능한 서비스
  selector:
    app: thegull # 이 레이블을 가진 파드에 트래픽을 전달
  ports:
    - port: 80 # 서비스가 사용하는 포트
      targetPort: 5000 # 파드 내 Flask 애플리케이션이 리슨하고 있는 포트
      nodePort: 30007 # 외부에서 접근 가능한 포트
